Tests
chechenque/MiniGit pull request #29
Opened 2024-05-05 15:17 UTC by AlbertNath

2024-05-05 15:39 UTC, chechenque requested changes

2024-05-05 15:39 UTC, chechenque commented on Minigit/src/test/java/kass/concurrente/Snapshots/WFSnapshotTest.java
> +
Recomendación

Usar:

@beforeEach
void setUp(){
//Codigo de inicializacion
}
(Modificacion no necesaria)

2024-05-05 15:39 UTC, chechenque commented on Minigit/src/test/java/kass/concurrente/Stamped/StampedSnapTest.java
> +        StampedValue<Integer> stampedValue2 = new StampedValue<>(10);
StampedValue<Integer> stampedValue2 = new StampedValue<>(10,10);

2024-05-05 15:39 UTC, chechenque commented on Minigit/src/test/java/kass/concurrente/Stamped/StampedSnapTest.java
> +        StampedValue<Integer> stampedValue2 = new StampedValue<>(10);
Sustituir easa linea

2024-05-05 15:39 UTC, chechenque commented on Minigit/src/test/java/kass/concurrente/Stamped/StampedSnapTest.java
> +
Documentación

2024-05-05 15:39 UTC, chechenque commented on Minigit/src/test/java/kass/concurrente/Snapshots/WFSnapshotTest.java
> +
Documentacion

2024-05-05 15:39 UTC, chechenque commented on Minigit/src/test/java/kass/concurrente/stash/StashTest.java
> +    private static Stash stash;
Puedes poner static {
//Todas las variables
}

(No es necesario, pero es para que Lo tomes en cuenta)

2024-05-05 17:25 UTC, AlbertNath commented on Minigit/src/test/java/kass/concurrente/stash/StashTest.java
> +    private static Stash stash;
Anotado

2024-05-05 20:35 UTC, Paolatae2505 commented on Minigit/src/test/java/kass/concurrente/Snapshots/WFSnapshotTest.java
> +
vale

2024-05-13 22:58 UTC, chechenque approved these changes

2024-05-13 22:58 UTC, merged